### ISSUE TITLE
Standalone version crash on ubuntu

### ISSUE THREAD

**Issue by brunosez** [jmvanel/semantic_forms#92]
Following install party :
bruno@ubuntu:~/semantic_forms/semantic_forms_play-1.0-SNAPSHOT$ bin/semantic_forms_play -J-Xmx50M 
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/typesafe/config/ConfigException : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at play.core.server.ProdServerStart$.readServerConfigSettings(ProdServerStart.scala:81)
	at play.core.server.ProdServerStart$.start(ProdServerStart.scala:42)
	at play.core.server.ProdServerStart$.main(ProdServerStart.scala:27)
	at play.core.server.ProdServerStart.main(ProdServerStart.scala)

With fresh Java8 install :java -version
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

**Comment by jmvanel** [comment]
On my desktop with Ubuntu 16.04 LTS the zip version work fine:
```
$ uname -a
Linux jmv-tour 4.4.0-31-generic #50-Ubuntu SMP Wed Jul 13 00:07:12 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

java -version
openjdk version "1.8.0_91"
OpenJDK Runtime Environment (build 1.8.0_91-8u91-b14-3ubuntu1~16.04.1-b14)
OpenJDK 64-Bit Server VM (build 25.91-b14, mixed mode)

which java 
/usr/lib/jvm/java-8-openjdk-amd64//bin/java
```

**Comment by jmvanel** [comment]
JAVA_HOME is set accordingly.
Bruno, can check that your JAVA_HOME is for Java 8 ?

```
echo $JAVA_HOME
/usr/lib/jvm/java-8-openjdk-amd64/
```

**Comment by brunosez** [comment]
echo $JAVA_HOME
/usr/lib/jvm/default-java
ll /usr/lib/jvm/default-java
lrwxrwxrwx 1 root root 24 mars  22  2014 /usr/lib/jvm/default-java -> java-1.7.0-openjdk-amd64/
it seems JAVA_HOME target to Java 7 !!

**Comment by jmvanel** [comment]
Try 

    unset JAVA_HOME

**Comment by jmvanel** [comment]
unset JAVA_HOME

has worked fine
